# ZT_Boosted 模块配置文件
# 如果配置错误模块会使用默认配置
# 会自动输出模块日志到 config.yaml.log
# 修改完之后记得重启喔

# 基于手表 CPU 的分配方案
# 用户后台应用（推荐: 0-1）
用户后台应用 0-1
# 系统后台应用（推荐: 0-2）
系统后台应用 0
# 前台应用（推荐: 0-3）
前台应用 0-3
# 上层应用（也就是悬浮窗啦）（推荐: 0-3）
上层应用 0-3

# 额外选项
# 这里是额外选项喔
# 看看里面有没有你中意的功能喔

# TCP 网络优化（默认推荐: 1）
# 0: 关闭网络优化
# 1: 开启网络优化
TCP网络优化 1

# 禁用模块日志输出（默认: 0）
# 0: 输出默认日志
# 1: 禁用日志功能
模块日志输出 0

# 开启无线 ADB 调试（默认: 0 端口: 5555）
# 0: 开启
# 1: 关闭
无线ADB调试 0

